haircut/urls.py
from django.urls import path
from . import views

app_name = 'haircut'
urlpatterns = [
	path('', views.home_page, name='home_page'),
]

salon/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('haircut.urls')),
    path('admin/', admin.site.urls),
]

haircut/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
     comment = models.CharField(max_length=180, null=True, blank=True)
     user = models.CharField(max_length=180, null=True, blank=True)

haircut/views.py
from django.shortcuts import render

def home_page(request):

	if request.method == 'POST':
		time = request.POST.get('time')
		customer_name = request.POST.get("customer_name")

		return render(request,'haircut/home_page.html',{'time':time,'customer_name': customer_name})

	return render(request, 'haircut/home_page.html' )

# Create your views here.

haircut/templates/haircut/home_page.html
<html>
<head>
	<title>Amazing Amy's Babershop</title>
</head>
<body>
	<h1>Amazing Amy's Babershop</h1>
	<p> A Fresh Cut For You and Your Family!</p>

	<h2>Here are our great babers!</h2>

	<!-- Baber 1 -->
	<p>Tony</p>
	<img src="http://tse3.mm.bing.net/th?id=OIP.XexYjoH8N4CVtVz2ebbOUwHaHa&w=204&h=203&c=7&o=5&pid=1.7">
	<br>
	<br>
	<!-- Baber 2 -->
	<p>Jane</p>
	<img src="http://tse1.mm.bing.net/th?id=OIP.v18ucxmbVMxruuDoi2KQTwAAAA&w=125&h=175&c=7&o=5&pid=1.7">
	<br>
	<br>
	<!-- Baber 3 -->
	<p>Jack</p>
	<img src="http://tse1.mm.bing.net/th?id=OIP.A2Jb4HxWfrSi8PesOAIgHgHaLL&w=142&h=209&c=7&o=5&pid=1.7">
	<br>
	<br>
	<!-- Baber 4 -->
	<p>Sunny</p>
	<img src="http://tse1.mm.bing.net/th?id=OIP.FeSGsA0IeAYFnOxBF0gZ3wHaJh&w=186&h=239&c=7&o=5&pid=1.7">
	<br>

	<!-- Order Form -->
	<h2>Place your Order</h2>
	<form action="{% url 'haircut:home_page' %}"method= "POST">
		{% csrf_token %}
		<input type="text" name="time" placeholder="Please Type Which Baber You Want"><br>
		<textarea name="customer_name" placeholder="Please Type Your Name&date" ></textarea><br>
		<input type="submit" value="Please Your Order">
	</form>

	<!-- Show Order -->
	<h1>Your Order:</h1>
	<p>Baber Ordered:{{time}}</p>
	<p>Customer and date:{{customer_name}}</p>



</body>
</html>